---
- name: run ifreload
  shell: ifreload -a

- name: save nxos config
  nxos_config:
    diff_against: startup
    diff_ignore_lines:
      - "^mac-address"
    save_when: modified
  diff: yes

- name: save eos config
  eos_config:
    diff_against: startup
    diff_ignore_lines:
    save_when: modified
    authorize: yes
  diff: yes
