---
system:
  config:
    hostname: arista01-leaf
routing:
  bgp:
    asn: 65014
    router_id: 10.100.1.5
    neighbors:
      - {ip: 10.3.3.0, asn: 65010}
      - {ip: 10.1.1.1, asn: 65011}

interfaces:
  "Ethernet1":
    switch_port_type: switch
    config:
      description: "cisco switch"
      ipv4:
        addresses:
          - "10.3.3.1/31"
  "Ethernet2":
    switch_port_type: server
    config:
      description: "server3"
      ipv4:
        addresses:
          - "10.200.1.4/31"
  "Loopback0":
    switch_port_type: loopback
    config:
      description: loopback
      ipv4:
        addresses:
          - "10.100.1.5/32"
