---
system:
  config:
    hostname: cisco01-spine

routing:
  bgp:
    asn: 65013
    router_id: 10.100.1.4
    neighbors:
      - {ip: 10.2.2.1, asn: 65012}
      - {ip: 10.1.1.1, asn: 65011}
      - {ip: 10.3.3.1, asn: 65014}

interfaces:
  "Ethernet2/1":
    switch_port_type: switch
    config:
      description: "Cumulus Switch"
      ipv4:
        addresses:
          - "10.2.2.0/31"

  "Ethernet2/2":
    switch_port_type: switch
    config:
      description: "Junos Switch"
      ipv4:
        addresses:
          - "10.1.1.0/31"


  "Ethernet2/3":
    switch_port_type: switch
    config:
      description: "Arista Switch"
      ipv4:
        addresses:
          - "10.3.3.0/31"

  "loopback0":
    switch_port_type: loopback
    config:
      description: Loopback port
      ipv4:
        addresses:
          - "10.100.1.4/32"
