---
system:
  config:
    hostname: cumulus01-leaf
routing:
  bgp:
    asn: 65012
    router_id: 10.100.1.3
    neighbors:
      - ip: 10.2.2.0
        asn: 65010

    redistribute:
      prefix_list:
        name: SERVER_PREFIXES
        entries:
          - cidr: 10.200.0.0/16
            prefix: 30
            operator: ge


interfaces:
  "swp1":
    switch_port_type: switch
    config:
      description: "cisco switch"
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "10.2.2.1/31"
  "swp2":
    switch_port_type: server
    config:
      description: "server2"
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "10.200.1.2/31"
  "lo":
    switch_port_type: loopback
    config:
      description: loopback
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "10.100.1.3/32"
