---
system:
  hostname: cumulus01-leaf
routing:
  bgp:
    asn: 65012
    router_id: 10.100.1.3
    neighbors:
      - ip: 10.2.2.0
        asn: 65010

    redistribute:
      prefix_list:
        name: SERVER_PREFIXES
        entries:
          - cidr: 10.200.0.0/16
            prefix: 30
            operator: ge

interfaces:

  switch:
    - name: swp1
      ipv4: 10.2.2.1/31
      description: cisco switch

  server: []
#    - name: swp2
#      ipv4: 10.200.1.2/31
#      description: server1

  loopback:
    - name: lo
      ipv4: "{{ routing.bgp.router_id }}/32"
