---
system:
  hostname: cumulus01-leaf
routing:
  bgp:
    asn: 65012
    router_id: 10.100.1.3
    neighbors:
      - ip: 10.2.2.0
        asn: 65010
    redistribute:
      - prefix_lists:
          - name: SERVER_PREFIXES
            entries:
              - cidr: 10.200.0.0/16
                prefix: 30
                operator: ge

interfaces:

  interswitch:
    - name: swp1
      address: 10.2.2.1/31
      description: cisco switch

  server:
    - name: swp2
      address: 10.200.1.2/31
      description: server1

  logical:
    - name: lo
      address: "{{ routing.bgp.router-id }}/32"
