---
system:
  hostname: junos01-leaf

routing:
  bgp:
    asn: 65011
    router_id: 10.100.1.3
    neighbors:
      - ip: 10.1.1.0
        asn: 65010
    redistribute:
      prefix_lists:
        - name: SERVER_PREFIXES
          entries:
            - cidr: 10.200.0.0/16
              prefix: 30
              operator: ge

interfaces:
  switch:
    - name: em4
      ipv4: 10.1.1.1/31
      description: cisco switch

  server:
    - name: em3
      ipv4: 10.200.1.0/31
      description: server1

  loopback:
    - name: lo0
      ipv4: "{{ routing.bgp.router_id }}/32"
