---
system:
  config:
    hostname: junos01-leaf

routing:
  bgp:
    asn: 65011
    router_id: 10.100.1.3
    neighbors:
      - ip: 10.1.1.0
        asn: 65010
    redistribute:
      prefix_lists:
        - name: SERVER_PREFIXES
          entries:
            - cidr: 10.200.0.0/16
              prefix: 30
              operator: ge

interfaces:
  "em4":
    switch_port_type: switch
    config:
      description: "cisco switch"
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "10.1.1.1/31"
  "em3":
    switch_port_type: server
    config:
      description: "server 1"
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "10.200.1.0/31"
  "lo0":
    switch_port_type: loopback
    config:
      description: loopback
      subinterfaces:
        "0":
          ipv4:
            addresses:
              - "{{ routing.bgp.router_id }}/32"
