---
system:
  config:
    hostname: junos01-leaf

routing:
  bgp:
    asn: 65011
    router_id: 10.100.1.2
    neighbors:
      - ip: 10.1.1.0
        asn: 65010
    redistribute:
      prefix_lists:
        - name: SERVER_PREFIXES
          entries:
            - cidr: 10.200.0.0/16
              prefix: 30
              operator: ge

interfaces:
  "xe-0/0/1":
    switch_port_type: switch
    config:
      description: "cisco switch"
      ipv4:
          addresses:
            - "10.1.1.1/31"
  "xe-0/0/0":
    switch_port_type: server
    config:
      description: "server 1"
      ipv4:
        addresses:
          - "10.200.1.0/31"
  "lo0":
    switch_port_type: loopback
    config:
      description: loopback
      ipv4:
        addresses:
          - "10.100.1.2"
