---
system:
  config:
    hostname: junos01-leaf

routing:
  bgp:
    asn: 65011
    router_id: 10.100.1.2
    neighbors:
      - ip: 10.1.1.0
        asn: 65010
    redistribute:
      prefix_lists:
        - name: SERVER_PREFIXES
          entries:
            - cidr: 10.200.0.0/16
              prefix: 30
              operator: ge
openconfig_interfaces:
  interface:
    - name: "em4"
      switch_port_type: switch
      config:
        description: "Cisco Switch"
        subinterfaces:
          subinterface:
            - index: 0
              ipv4:
                addresses:
                  address:
                    - ip: "10.1.1.0/31"

    - name: "em3"
      switch_port_type: switch
      config:
        description: "server 1"
        subinterfaces:
          subinterface:
            - index: 0
              ipv4:
                addresses:
                  address:
                    - ip: "10.200.1.0/31"

    - name: "lo0"
      switch_port_type: loopback
      config:
        description: "loopback"
        subinterfaces:
          subinterface:
            - index: 0
              ipv4:
                addresses:
                  address:
                    - ip: "{{ routing.bgp.router_id }}/32"
