---
- name: get show interface output
  nxos_command:
    commands: "show interface {{ iface.name }}"
  register: iface_output

- name: facts from ethernet interface
  set_fact:
    iface_details: "{{ iface_output.stdout[0] | parse_cli('./parsers/nxos/show_int_parser.yml') }}"

- debug: var=iface_details

  #- name: check that interface is up and IP is correctly assigned
  #assert:
  #  that:
  #    - "iface_details[0]['LINK_STATUS'] == 'up'"
  #    - "iface_details[0]['IP_ADDRESS'] == '{{ iface.ipv4 }}'"
  #  msg: "Failed"

