---
- name: get show interface output
  nxos_command:
    commands: "show interface {{ iface.name }}"
  register: iface_output

- name: facts from ethernet interface
  set_fact:
    nxos_interface: "{{ iface_output.stdout[0] | parse_cli('./parsers/nxos/nxos_show_interface_parser.yml') }}"

- name: check that interface is up and IP is correctly assigned
  assert:
    that:
      - "nxos_interface[0].link_protocol_state == 'up'"
      - "nxos_interface[0].ipv4  == '{{ iface.ipv4 }}'"
    msg: "NXOS interface {{ iface.name }} failed test. Is either not Up or IP address is not correct"
